export const projects = [
	{
		id: "millionaire",
		tech: "React • Redux • Firebase",
		name: "Javascript Millionaire App",
		imgSrc: "javascript-millionaire",
		projectLink: "https://rlnb2022.github.io/Javascript-Millionaire/",
		githubLink: "https://github.com/rlnB2022/Javascript-Millionaire",
		description: [
			"<p>To strengthen my knowledge of React and understand how to use a database with a React app, I created this app. I have updated the app to utilize Redux for state management.</p>",
			"<ul><li>React</li><li>useState / UseEffect Hooks</li><li>Firebase</li><li>HTML</li><li>CSS</li><li>Javascript</li></ul>",
			"<p>Having never used Firebase/Firestorm before, I took it as a challenge. (I love learning new things!) Reading through the Firestorm docs and walking through the setup process on their website wasn't too difficult.</p><p>I had an issue with too many renderings when I implement the Timer component from App.js. Instead of counting down from 30 when the game starts and the question is revealed, it began immediately. I moved the logic to the Timer component and that helped tremendously.</p><p>I used SVG images for each question/answer. I ran into a problem where the SVGs wouldn't resize to fit the grid. I replaced the SVGs with simple borders/border-radius styles applied. I understand that the viewbox setting in the SVG might be the culprit. I'll have to learn more about using SVGs to understand how to implement something like this in the future.</p>",
			"<p>I learned that React is the library that was just made for me. I love it! Firestore databases are amazing. Coming from a SQL background, a noSQL database with documents wasn't as difficult as I thought it would be. Implementing React Redux to manage the state of the app was also not as difficult as I expected, either. At my current job, we used Flux, so it was easy to adapt and learn.</p>",
		],
	},
	{
		id: "digidugout",
		tech: "PHP • Javascript • jQuery • AJAX",
		name: "DigiDugout Website",
		imgSrc: "digidugout",
		projectLink: "https://www.digidugout.com",
		githubLink: "https://github.com/rlnB2022/digi-new-scoresheets",
		description: [
			"<p>This website was created for a specific gaming niche, Tabletop Baseball Gaming. These games use baseball player cards and dice. Games like Strat-O-matic, APBA, Payoff Pitch, etc. all fit into this category. They also all have the same exact issue which is the immense amount of time that it takes to set the game up. This is where I got the idea to create DigiDugout.com.</p><br /><h2>Features:</h2><ul><li>mySQL database with tables for all players that have ever played the game along with the lineups for each game ever played</li><li>Custom date selector with month and year selectors.</li><li>Team names displayed with color-coded background and fonts.</li><li>View, at a glance, the real-life winning and losing pitchers as well as who earned the save. Also displays the runs, hits and errors.</li><li>View the lineups for each team</li><li>'Print scoresheet' button will popup a pdf file for printing.</li><li>Lineups and starting pitchers are pre-filled</li></ul>",
			"<ul><li>PHP</li><li>Javascript</li><li>jQuery</li><li>HTML</li><li>CSS</li><li>AJAX</li></ul>",
			"<p>My goal was simple. Create a website where users don't have to do any online research; they don't have to write the lineups and starting pitchers on a blank score sheet by hand; they can just find the game and click print score sheet.</p><p>I knew what I wanted to build. I knew who my audience was and why they would want to use this resource. I just didn't know what Tech to use to accomplish my goals.</p><p>So, I did some research. Mainly into how to access a database from a website that I would create. I stumbled across some YouTube videos on PHP that showed how to connect, read, update, and delete data. It seemed fairly simple so I moved forward.</p><p>Next, I looked into web-hosting and found that there were cheap hosting services that used phpMyAdmin, so I went with it. From that point forward, I was learning PHP 'on-the-job'. I used php.net/docs often, as well as StackOverflow and standard Google searches to find what I was looking for.</p><p>I went through a number of iterations on the design for the website before settling on the current version. I really just wanted the website to be simple to use and straight to the point. I used lined-notebooks and blank sheets of copy paper to draw out ideas. It wasn't until many months later that I discovered Figma, but never used it with this project.</p>",
			"<p>In the beginning, I struggled to get things to work as intended as I was completely new to PHP, AJAX and jQuery. It took a monumental effort to learn these technologies during the development process.</p><p>I learned a lot with this project. New tech, new methods of fetching data, and I even learned that if I don't like the way built-in Date Objects work, I can make my own.</p><p>I'm certain the code can be improved upon, but I'm super proud of the work I did on this!</p><p>Throughout the development process, I continued to learn not only about PHP, but jQuery and AJAX. I learned that they go hand-in-hand and this allowed me to fetch data without reloading the page. I thought that was so cool!</p>",
		],
	},
	{
		id: "twobarrels",
		tech: "React • React Router • FontAwesome",
		name: "React Two Barrels Website",
		imgSrc: "twobarrels",
		projectLink: "https://rlnb2022.github.io/twobarrels/",
		githubLink: "https://github.com/rlnB2022/twobarrels",
		description: [
			"<p>I am highly impressed with Two Barrels for their core values, the freedom given to developers to try new things out even if they fail miserably and overall - the way their website speaks to me. I wanted to show my enthusiasm for Two Barrels and use the knowledge that I have to reproduce their website and show that I can do what is required for the job, even when using a library like React. Using the skills that I have, I created this website using React and React Router.</p><p>This project uses 40 components, each with their own integrated stylesheet.</p>",
			"<ul><li>React</li><li>React Router</li><li>useState and useEffect Hooks</li><li>HTML</li><li>CSS</li><li>Javascript</li></ul>",
			"<p>Knowing that this website should be created using regular HTML, CSS, and Javascript - or Wordpress, I wanted to use the skills I have in React to create this website, as ridiculous as that may seem (using the wrong tech for the job).</p><p>I went through every single page and read every single word of this website to get an understanding of what components would be needed.</p><p>I used a mobile-first design, then added styles to accomodate tablet and desktop</p><p>The end result turned out great!</p>",
			"<p>I learned that using React Router published to Github pages doesn't work well when typing into the address bar to get to a specific page.</p><p>This was a really fun project to build and has accelerated my confidence working with React.</p><p><strong>Two Barrels:</strong> What a great website! Whoever wrote the content for your website deserves a raise, I'm very impressed.</p>",
		],
	},
	{
		id: "amazon",
		tech: "React • Redux • Firebase • React Router",
		name: "Amazon Clone",
		imgSrc: "amazon-clone",
		projectLink: "https://clone-332d9.web.app/",
		githubLink: "https://github.com/rlnB2022/amazon-clone",
		description: [
			"<p>This was another proejct that I started to get a better understanding of React and React Router. Using the Firebase User Authentication system, shopping carts and maybe one day, payment systems.</p><p>In this project, you can sign up as a new user and sign in/sign out. Clicking the cart brings you to your shopping cart which displays all of the products that were added.</p>",
			"<ul><li>React</li><li>React Redux</li><li>React Router</li><li>Firebase (user authentication)</li><li>useState / UseEffect Hooks</li><li>HTML</li><li>CSS</li><li>Javascript</li></ul>",
			"<p>Using the real amazon.com website as a reference, I mocked up a one-page wireframe on paper (probably should have used Figma). Although the search bar and various other links don't work, I wanted to focus mainly on the login system and the shopping cart.</p>",
			"<p>This was a really fun project to learn about Firebase Auth and shopping carts using React Redux. One day I'll get back to it and finish the mobile/tablet design. I'm not happy that I skipped this part of development and in fact, developed this backwards.</p><p>Creating a user is currently not working. I'll need to take a look at this when I have time.</p><p>Overall, I happy with how the website turned out!</p>",
		],
	},
];
